apiVersion: v1
kind: Pod
metadata:
  name: k8-demo
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
  - name: sidecar
    image: barniemakonda/sidecar:v0.0.1
    ports:
        - containerPort: 8081
